# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart N Flutter

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: test-dart-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dependencies check
        uses: geowatson/flutter-latest@1.0.0
        with:
          args: pub get
      - name: analyze code
        uses: geowatson/flutter-latest@1.0.0
        with:
          args: analyze
      - name: tests!!
        uses: geowatson/flutter-latest
        with:
          args: test
